CREATE TABLE devices (
     PIE_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
     IP VARCHAR(32),
     PORT INT,
     MAC VARCHAR(32)
);

CREATE TABLE device_data (
     ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
     PIE_ID INT NOT NULL,
     TEMP FLOAT,
     AIR_HUMID FLOAT,
     PPM FLOAT,
     SOIL_MOISTURE FLOAT,
     PRESSURE FLOAT,
     DATE DATE,
     FOREIGN KEY (PIE_ID) REFERENCES devices(PIE_ID)
);
