version: '3.8'

services:

  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data

  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - seq
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      port: 3000
      NODE_ENV: development
      SEQ_URL: http://seq:5341

volumes:
  seq_data:
